vim.opt.number = true          -- line numbers
vim.opt.relativenumber = true  -- relative line numbers
vim.opt.tabstop = 2            -- 2 space tabs
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.signcolumn = "yes"
vim.opt.clipboard = "unnamedplus"  -- system clipboard
