# --- MARCOS ---
$mainMod = SUPER
$terminal = kitty

# --- MONITOR ---
monitor=eDP-1,1920x1080@60,0x0,1

# --- INPUT & TOUCHPAD ---
input {
	kb_layout = us
	follow_mouse = 1
	float_switch_override_focus = 1
	touchpad {
 		natural_scroll = true
	tap-to-click = true
	drag_lock = true
	}
}
general {
	layout = dwindle
}

# --- VISUALS ---
decoration  {
	rounding = 12
	active_opacity = 0.9
	inactive_opacity = 0.8

	blur {
		enabled = true
		size = 10
		passes = 4
		new_optimizations = true
		xray = true
		noise = 0.02
		contrast = 1.1
		brightness = 1.0
		vibrancy = 0.2
	}
	shadow {
		enabled = true
		range = 15
		render_power = 3
		color = rgba(1a1a1aee)
	}
}

# --- ACCENT COLORS ---

$gold = rgb(ffcc00)
$orange = rgb(ff6600)

general {
	gaps_in = 5 
	gaps_out = 10
	border_size = 2
	col.active_border = $gold $orange 45deg
	col.inactive_border = rgba(595959aa)
}

# --- WINDOW RULES ---
windowrule = match:class ^(kitty)$, opacity 0.8 0.7

# --- LAYER RULES ---
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.0, match:namespace waybar

# --- WORKSPACE ASSIGNMENTS ---
windowrule = workspace 1, match:class ^(firefox)$
windowrule = workspace 2, match:class ^(kitty)$
windowrule = workspace 3, match:class ^(code)$
windowrule = workspace 4, match:class ^(discord)$
windowrule = workspace 5, match:class ^(steam)$
windowrule = workspace 6, match:class ^(thunar)$

windowrule = float on, match:title ^(update)$
windowrule = size 700 500, match:title ^(update)$
windowrule = center 1, match:title ^(update)$

# --- KEYBINDINGS --- 
bind = $mainMod, Escape, exec, wlogout -b 5 -m 10
bind = $mainMod, L, exec, ~/.config/hypr/scripts/lock.sh
bind = $mainMod, U, exec, kitty --title update -e ~/.config/hypr/scripts/update.sh

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, D, exec, rofi -show drun -modi drun
bind = $mainMod, C, killactive,
bind = $mainMod, F, fullscreen, 0
bind = $mainMod, V, togglefloating,

bind = $mainMod ALT, W, exec, ~/.config/hypr/scripts/wall_shuffle.sh

binde = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
binde = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

binde = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
binde = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3

# --- SCREENSHOTS ---
bind = , Print, exec, grim - | wl-copy
bind = $mainMod, X, exec, grim -g "$(slurp)" - | wl-copy

# --- VIEW CHIPBOARD HISTORY ---
bind = $mainMod, B, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy

# --- AUTOSTART ---
exec-once = sleep 1 && waybar
exec-once = swww-daemon --format xrgb
exec-once = sleep 1 && ~/.config/hypr/scripts/wall_loop.sh
exec-once = nm-applet --indicator
exec-once = wl-paste --watch cliphist store
exec-once = nwg-dock-hyprland -x -d 3000 -i 24
exec-once = swaync
exec-once = hypridle
exec-once = blueman-applet
